---
title: "project_4"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(mosaic)
library(tidyverse)
```

## Analysis and Discussion

```{r}
data <- read.csv("C:/Users/space/repo/ProbabilityApplications_ANOVAOfSortingAlgorithm/src/data.csv")
data %>% head(5)
```


```{r}
data$size[data$size==1000000] <- 'small'
data$size[data$size=='2000000'] <- 'medium'
data$size[data$size=='3000000'] <- 'large'
```


```{r}
data['original_sorting'] %>% unique()
```


```{r}
data <- data %>%
  filter(original_sorting %in% c('normal(0,1)', 'uniform(0,1)', 'gamma(1,1)'))
```


```{r}
anova.base <- aov(time ~ size + original_sorting, data = data)
summary(anova.base)
```


```{r}
anova.interaction <- aov(time ~ size * original_sorting, data = data)
summary(anova.interaction)
```



```{r}
mean(time ~ size + original_sorting, data = data)
```


```{r}
qplot(anova.base$fitted.values,anova.base$residuals) + 
  geom_hline(yintercept = 0, color = "darkgreen")

ggplot() +
  geom_qq(aes(sample=anova.base$residuals)) + 
  geom_qq_line(aes(sample=anova.base$residuals))

qplot(anova.base$residuals,geom = "histogram", bins=15)
```














